# Generated by Django 4.1.5 on 2023-01-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='worker',
            field=models.BooleanField(default=False),
        ),
    ]
