# Generated by Django 4.1.5 on 2023-01-02 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_client_user_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=50, null=True, verbose_name='lastname')),
                ('firstname', models.CharField(max_length=50, null=True, verbose_name='firstname')),
                ('birthday', models.CharField(max_length=60, null=True)),
                ('sex', models.CharField(max_length=60, null=True)),
                ('bio', models.TextField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
