# Generated by Django 4.1.5 on 2023-05-16 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ref_dom_btp', '0003_domaine_image'),
        ('account', '0005_user_adresse_user_datenais_user_nom_user_prenom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employeur',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('account.user',),
        ),
        migrations.CreateModel(
            name='Gestionnaire',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('account.user',),
        ),
        migrations.RemoveField(
            model_name='user',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='user',
            name='client',
        ),
        migrations.RemoveField(
            model_name='user',
            name='datenais',
        ),
        migrations.RemoveField(
            model_name='user',
            name='worker',
        ),
        migrations.AddField(
            model_name='user',
            name='adress',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='civilite',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('metier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ref_dom_btp.metier')),
            ],
            options={
                'abstract': False,
            },
            bases=('account.user',),
        ),
    ]
