# Generated by Django 4.1.5 on 2023-05-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_workerprofile_gestionnaireprofile_employeurprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestionnaireprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='worker',
            name='annee_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worker',
            name='nombre_davis',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worker',
            name='nombre_jobs',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='EmployeurProfile',
        ),
        migrations.DeleteModel(
            name='GestionnaireProfile',
        ),
        migrations.DeleteModel(
            name='WorkerProfile',
        ),
    ]
