# Generated by Django 4.1.5 on 2023-05-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_gestionnaireprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_naiss',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ville',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
