# Generated by Django 4.1.5 on 2023-05-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_date_naiss_user_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='adress',
            field=models.CharField(default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_naiss',
            field=models.CharField(default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ville',
            field=models.CharField(default='', max_length=60, null=True),
        ),
    ]
