# Generated by Django 4.1.5 on 2023-05-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_user_adress_alter_user_civilite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
