# Generated by Django 4.1.5 on 2023-05-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_user_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workers', models.ManyToManyField(related_name='workers', to='account.worker')),
            ],
        ),
        migrations.AddField(
            model_name='worker',
            name='competences',
            field=models.ManyToManyField(related_name='competences', to='account.competence'),
        ),
    ]
