# Generated by Django 4.1.5 on 2023-05-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_worker_competences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='competences',
            field=models.ManyToManyField(blank=True, related_name='competences', to='account.competence'),
        ),
    ]
