# Generated by Django 4.1.5 on 2023-05-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_worker_competences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='workers',
            field=models.ManyToManyField(blank=True, related_name='workers', to='account.worker'),
        ),
    ]
