# Generated by Django 4.1.5 on 2023-07-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref_dom_btp', '0008_remove_metier_travaux_remove_travaux_metier'),
        ('account', '0017_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='canDo',
            field=models.ManyToManyField(to='ref_dom_btp.travaux'),
        ),
    ]
