# Generated by Django 4.1.5 on 2023-08-23 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gest_qual_ouvrier', '0004_remove_competence_ouvrier_id_competence_and_more'),
        ('gest_offres', '0004_alter_reservation_employeur_alter_reservation_worker'),
        ('ref_dom_btp', '0009_metier_task'),
        ('account', '0018_worker_cando'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Worker',
            new_name='Ouvrier',
        ),
    ]
