# Generated by Django 4.1.5 on 2023-05-18 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
