# Generated by Django 4.1.5 on 2023-05-16 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_user_tel'),
        ('gest_qual_ouvrier', '0002_competence_created_at_competence_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_experience', to='account.worker'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_certify', to='account.worker'),
        ),
    ]
