# Generated by Django 4.1.5 on 2023-05-17 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_competence_worker_competences'),
        ('gest_qual_ouvrier', '0003_alter_experience_worker_alter_formation_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence_ouvrier',
            name='id_competence',
        ),
        migrations.RemoveField(
            model_name='competence_ouvrier',
            name='worker',
        ),
        migrations.AlterField(
            model_name='experience',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.worker'),
        ),
        migrations.DeleteModel(
            name='Competence',
        ),
        migrations.DeleteModel(
            name='Competence_Ouvrier',
        ),
    ]
