# Generated by Django 4.1.5 on 2023-05-17 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0016_alter_competence_workers'),
        ('ref_dom_btp', '0003_domaine_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.DateField()),
                ('heure', models.TimeField(default='01:00:00')),
                ('description', models.TextField()),
                ('lieu', models.CharField(max_length=100)),
                ('statut', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employeur', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='employeur_offres', to='account.employeur')),
                ('id_domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domaine_offre', to='ref_dom_btp.domaine')),
                ('id_travaux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offre_travaux', to='ref_dom_btp.travaux')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('code', models.CharField(max_length=60, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employeur', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='employeur_reserve', to='account.employeur')),
                ('id_offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_doffre', to='gest_offres.offre')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ouvrier_reserver', to='account.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaire_doffre', to='gest_offres.offre')),
                ('worker', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='workers_commentaire', to='account.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Appreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employeur', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='appreciation_employeur', to='account.employeur')),
                ('id_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appreciation_reserver', to='gest_offres.reservation')),
            ],
        ),
    ]
