# Generated by Django 4.1.5 on 2023-06-25 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gest_offres', '0002_alter_offre_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='employeur',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='employeur_offres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='code',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
