# Generated by Django 4.1.5 on 2023-06-25 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gest_offres', '0003_alter_offre_employeur_alter_reservation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='employeur',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='employeur_reserve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ouvrier_reserver', to=settings.AUTH_USER_MODEL),
        ),
    ]
