# Generated by Django 4.1.5 on 2023-07-06 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ref_dom_btp', '0004_metier_travaux'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metier',
            name='travaux',
        ),
    ]
