# Generated by Django 4.1.5 on 2023-07-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref_dom_btp', '0005_remove_metier_travaux'),
    ]

    operations = [
        migrations.AddField(
            model_name='travaux',
            name='metier',
            field=models.ManyToManyField(to='ref_dom_btp.metier'),
        ),
    ]
