# Generated by Django 4.1.5 on 2023-07-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref_dom_btp', '0006_travaux_metier'),
    ]

    operations = [
        migrations.AddField(
            model_name='metier',
            name='travaux',
            field=models.ManyToManyField(related_name='metiers_travaux', to='ref_dom_btp.travaux'),
        ),
        migrations.AlterField(
            model_name='travaux',
            name='metier',
            field=models.ManyToManyField(related_name='travaux_metier', to='ref_dom_btp.metier'),
        ),
    ]
