# Generated by Django 4.1.5 on 2023-07-08 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref_dom_btp', '0008_remove_metier_travaux_remove_travaux_metier'),
    ]

    operations = [
        migrations.AddField(
            model_name='metier',
            name='task',
            field=models.ManyToManyField(to='ref_dom_btp.travaux'),
        ),
    ]
